# Generated by Django 3.2.11 on 2022-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0002_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='student_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
