# Generated by Django 3.2.11 on 2022-01-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0003_student_info_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='name',
            new_name='student_name',
        ),
    ]
