# Generated by Django 3.2.11 on 2022-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0004_rename_name_student_info_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
