# Generated by Django 3.2.11 on 2022-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0005_auto_20220126_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
