# Generated by Django 3.2.11 on 2022-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_app', '0006_alter_student_info_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
